version: "3"
services:
  nginx-revproxy:
    build: ./nginx-revproxy
    ports: 
      - 80:80
      - 443:443
    depends_on:
      - web
    environment:
      WORKER_PROCESSES: 2
      WORKER_CONNECTIONS: 1024
      KEEPALIVE_TIMEOUT: 65
      GZIP: "on"
      BACKEND_HOST: web:8000
      BACKEND_MAX_FAILS: 3
      BACKEND_FAIL_TIMEOUT: 10s
      SERVER_NAME: matsura-yuma.site
      SERVER_PORT: 80
      LOG_STDOUT: "false"
      STATIC_FOLDER: /static/
    volumes:
      - ./web/static:/static
    networks: 
      - nginx_network

  web:
    build: ./web
    expose:
      - "8000"
    restart: always
    volumes:
      - ./web:/opt/portfolio
#      - static:/opt/portfolio/static
    environment:
      DEBUG: "False"
    networks:
      - nginx_network

#volumes:
#  static:

networks:
  nginx_network:
    driver: bridge