# Environment variables
# - HOST_NAME
# - USER_NAME
 
version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-browsers
    branches:
      only:
        - master
 
    steps:
      - checkout
 
      - add_ssh_keys:
          fingerprints:
            - "b4:e8:ea:ed:2f:72:75:fb:07:96:7d:b9:5b:b7:4f:95"
 
      - run:
          name: Start ssh-keyscan
          command: |
            ssh-keyscan ${HOST_NAME} >> ~/.ssh/known_hosts
 
      - deploy:
          name: Deploy
          command: |
            ssh $USER_NAME@$HOST_NAME \
            '~/deploy.sh;'
            #  docker container exec -it portfolio_nginx-revproxy_1 "bash; cmd.sh" '
